name: Regression Test

on: [pull_request]

jobs: 
  test:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        
      - name: Install Robot
        run:  pip install robotframework

      - name: Install Selenium
        run: pip install selenium robotframework-selenium2library webdrivermanager

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest
        run: chrome --version

      - name: Create folder for reports
        run: mkdir reports

      - name: Robot Framework Test
        run: robot test_cases/login_form.robot
