name: Regression Test

on: [pull_request]

jobs: 
  test:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Robot Framework
        uses: joonvena/robotframework-docker-action@v1.0
        env:
            BROWSER: chrome
            ROBOT_TESTS_DIR: ${{ github.workspace }}/test_cases
